name: CI

on:
  push:
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-versions: [ 8.2 ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Install dependencies
        uses: php-actions/composer@v6
      - name: Install PHP-CS-Fixer
        uses: php-actions/composer@v6
        with:
          working_dir: "tools/php-cs-fixer"
      - name: Install PHPStan
        uses: php-actions/composer@v6
        with:
          working_dir: "tools/phpstan"
      - uses: actions/cache@v3
        with:
          path: .php-cs-fixer.cache
          key: ${{ runner.OS }}-${{ github.repository }}-phpcsfixer-${{ github.sha }}
          restore-keys: |
            ${{ runner.OS }}-${{ github.repository }}-phpcsfixer-
      - name: Run PHP-CS-Fixer
        run: composer format-check
      - name: Run PHPStan
        run: composer lint
